//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersHandling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codes()
        {
            this.OrderLines = new HashSet<OrderLines>();
            this.Surface = new HashSet<Surface>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<double> Perimeter { get; set; }
        public int SubType { get; set; }
        public Nullable<double> Weigth { get; set; }
        public Nullable<int> ForeignID { get; set; }
        public int DefaultMU { get; set; }
        public Nullable<int> System { get; set; }
        public string SecondCode { get; set; }
        public Nullable<int> DefaultSupplier { get; set; }
        public Nullable<int> CoatingGroup { get; set; }
        public Nullable<double> DefaultLength { get; set; }
        public Nullable<int> DefaultSurface { get; set; }
        public int PF { get; set; }
        public int TF { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual CoatingGroup CoatingGroup1 { get; set; }
        public virtual MU MU { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual SubTypes SubTypes { get; set; }
        public virtual Systems Systems { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLines> OrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Surface> Surface { get; set; }
        public virtual Surface Surface1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
