//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersHandling
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLines
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int CodeID { get; set; }
        public int SurfaceID { get; set; }
        public double Pcs { get; set; }
        public Nullable<double> Length { get; set; }
        public double QTY { get; set; }
        public Nullable<double> RemainingQTY { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Comment { get; set; }
        public int IsForCoating { get; set; }
        public double SqmCorrections { get; set; }
        public int ThermoFilm { get; set; }
        public int ProtectiveFilm { get; set; }
        public Nullable<double> ThermoFilmPrice { get; set; }
        public Nullable<double> ProtectionFilmPrice { get; set; }
        public Nullable<double> Perimeter { get; set; }
        public Nullable<double> Weight { get; set; }
    
        public virtual Codes Codes { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Surface Surface { get; set; }
    }
}
