//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersHandling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderLines = new HashSet<OrderLines>();
            this.UploadedFiles = new HashSet<UploadedFiles>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ForeignID { get; set; }
        public int Customer_ID { get; set; }
        public System.DateTime Orddate { get; set; }
        public Nullable<System.DateTime> Deldate { get; set; }
        public int RALID { get; set; }
        public int Powder_Code { get; set; }
        public string Comment { get; set; }
        public int Compleated { get; set; }
        public Nullable<double> OrderValue { get; set; }
        public Nullable<double> OrderSQM { get; set; }
        public Nullable<double> Orderkgr { get; set; }
        public Nullable<double> OrderPcs { get; set; }
        public int IsConfirmed { get; set; }
        public int IsOffer { get; set; }
        public string Project { get; set; }
        public Nullable<System.DateTime> Req_date { get; set; }
        public Nullable<System.DateTime> Mat_date { get; set; }
        public int IsReady { get; set; }
        public Nullable<System.DateTime> Delivery_date { get; set; }
        public Nullable<System.DateTime> MatDate2 { get; set; }
        public Nullable<System.DateTime> ExpectedMatDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLines> OrderLines { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Codes Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedFiles> UploadedFiles { get; set; }
    }
}
