//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersHandling
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerCoatingGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerCoatingGroup()
        {
            this.CoatingPrices = new HashSet<CoatingPrices>();
            this.Partners = new HashSet<Partners>();
        }
    
        public int ID { get; set; }
        public string CoatingGroupName { get; set; }
        public Nullable<double> MinimumQTY { get; set; }
        public Nullable<double> ExpenseQTY { get; set; }
        public Nullable<int> DefaultMu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoatingPrices> CoatingPrices { get; set; }
        public virtual MU MU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
