//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersHandling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Codes = new HashSet<Codes>();
            this.Orders = new HashSet<Orders>();
            this.Users = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public string Partner_name { get; set; }
        public string VAT { get; set; }
        public string Email { get; set; }
        public string MRP { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> CoatingGroup { get; set; }
        public int DefaultTF { get; set; }
        public int DefaultPF { get; set; }
        public double DefaultTFPrice { get; set; }
        public double DefaultPFPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codes> Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
        public virtual PartnerCoatingGroup PartnerCoatingGroup { get; set; }
    }
}
